title: Research & Recreation Blog
email: research@deeg.xyz
description: >- # this means to ignore newlines until "baseurl:"
  Private research & recreation blog of Matthias Deeg
baseurl: /
url: https://research.deeg.xyz/
twitter_username: matthiasdeeg
github_username:  mdeeg

# Build settings
#theme: minima
remote_theme: mdeeg/minima

author:
  name: Matthias Deeg
  email: "research@deeg.xyz"

minima:
  skin: classic

  social_links:
      twitter: matthiasdeeg
      github: mdeeg

plugins:
  - jekyll-feed
