title: Research Blog
email: research@deeg.xyz
description: >- # this means to ignore newlines until "baseurl:"
  Private research blog of Matthias Deeg
baseurl: /
url: https://research.deeg.xyz/
twitter_username: matthiasdeeg
github_username:  mdeeg

# Build settings
#theme: minima
remote_theme: mdeeg/minima

minima:
  skin: dark

plugins:
  - jekyll-feed
